### PR TITLE
display error messages on COM error

### PR DESCRIPTION
**Pull request by otahirs**

### CODE REVIEW

**Comment by otahirs** [comment]
Screenshot from 2020-01-10 16-26-38
Screenshot from 2020-01-10 16-26-18
Screenshot from 2020-01-10 15-03-23

**Comment by fvacek** [comment]
dik :)

**Comment by jmacura** [comment]
Ty hlášky by měly být spíš:
"There are no ports available"
a
"Selected port /dev/ttyUSB1 is not available" (překlep ve slově "available")

Just my 2 cents..

**Comment by otahirs** [comment]
#497

**Pull request merged**
